# SwiftLint Configuration for LightRoll Cleaner
# Reference: https://realm.github.io/SwiftLint/rule-directory.html

# 対象ディレクトリ
included:
  - src

# 除外ディレクトリ
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - Tests

# 有効化するルール
opt_in_rules:
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# 無効化するルール
disabled_rules:
  - todo  # TODOコメントを許可
  - trailing_whitespace  # 空白末尾を許可（IDEで管理）

# ルール設定
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 600

type_body_length:
  warning: 250
  error: 400

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - i
    - j
    - x
    - y

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# カスタムルール
custom_rules:
  # 写真データのネットワーク送信を禁止
  no_photo_network_transmission:
    name: "No Photo Network Transmission"
    regex: "(URLSession|Alamofire|AF\\.).*(?:photo|image|PHAsset)"
    message: "写真データのネットワーク送信は禁止されています"
    severity: error

  # 強制アンラップの使用を警告
  force_unwrap_warning:
    name: "Force Unwrap Warning"
    regex: "\\!(?!\\=)"
    message: "強制アンラップの使用は避けてください。guard letまたはif letを使用してください"
    severity: warning

  # MainActorなしでのUI状態変更を警告
  main_actor_required:
    name: "MainActor Required"
    regex: "@Published(?!.*@MainActor)"
    message: "@Publishedプロパティを持つクラスには@MainActorを付与してください"
    severity: warning

# レポーター設定
reporter: "xcode"
